#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftFront,     tmotorTetrix, openLoop, encoder, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     rightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    rampDrop,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    rampLease,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    tail,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    drawBridge,           tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
•-1 = No Button Pressed
•0 = Gray Rectangle button.
•1 = Right Arrow button.
•2 = Left Arrow button.
•3 = Orange Square button.
*/
task main()
{
	nxtDisplayTextLine(7, "down 						up");
	while(1)
	{
		if(nNxtButtonPressed == 1)
			motor[lift] = 50;
		else if(nNxtButtonPressed == 2)
			motor[lift] = -50;
		else
			motor[lift] = 0;
	}
}
