#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*programmer: Druetord	date started: 12-28-15  update: 12-28-14
Just a program for the rubber wheels; when the joysticks are pushed
beyond our deadzone of 10, the values of the joysticks are scaled
for the 128/127 joystick range into the 100 motor range and motors are
set to the resulting power*/

const int deadZone = 10;
const float scale = .7874015748; //  100/127

#include "joystickDriver.c"
#define butta joy2Btn(2)
#define buttb joy2Btn(3)
#define buttx joy2Btn(4)
#define butty joy2Btn(5)
#define start joy2Btn(6)

const int targ1 = 1120, targ2 = 1120 * 2, targ3 = 1120 * 3, targ4 = 1120 * 4, targ5 = 1120 * 5;

void driveTrain(float y1, float y2)
{
	y1 *= -scale;
	y2 *= -scale;

	motor[Left] = y1;
	motor[Right] = y2;

}



void conveyorbelt(bool butt1, bool butt2)  //function to operate the conveyor belt
{
	if(butt1 == true)
	{
		motor[conveyor] = 100;
	}

	else if(butt2 == true)
	{
		motor[conveyor] = -100;
	}
}

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if((abs(joystick.joy1_y1) > deadZone) || (abs(joystick.joy1_y2) > deadZone))
		{
			nxtDisplayTextLine(6, "inside");
			driveTrain(joystick.joy1_y1, joystick.joy1_y2);
		}

		else
		{
			motor[Left] = 0;
			motor[Right] = 0;
		}

		if(joy1Btn(1) == true || joy1Btn(2) == true)   //if button one or two is pressed, run the motor accordingly
		{
			conveyorbelt(joy1Btn(5), joy1Btn(6));
		}
		else
			motor[conveyor] = 0;

	}



	//_________________________________________________________________________________________________________________________________
	int pos = 0;

	if (butta)
		pos =1;
	else if (buttb)
		pos=2;
	else if (buttx)
		pos=3;
	else if (butty)
		pos=4;
	else if (start)
		pos=5;

	switch (pos)
	{
	case 1:
		if(nMotorEncoder[lift] < targ1)
			motor[lift] = 100;
		else
		{
			motor[lift] = 0;
			pos = 0;
		}
		break;

	case 2:
		if(nMotorEncoder[lift] < targ2)
			motor[lift] = 100;
		else
		{
			motor[lift] = 0;
			pos = 0;
		}
		break;

	case 3:
		if(nMotorEncoder[lift] < targ3)
			motor[lift] = 100;
		else
		{
			motor[lift] = 0;
			pos = 0;
		}
		break;

	case 4:
		if(nMotorEncoder[lift] < targ4)
			motor[lift] = 100;
		else
		{
			motor[lift] = 0;
			pos = 0;
		}
		break;

	case 5:
		if(nMotorEncoder[lift] < targ5)
			motor[lift] = 100;
		else
		{
			motor[lift] = 0;
			pos = 0;
		}
		break;
		//_______________________________________________________________________________________________________________________________

  }
}
