#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void spin(bool butt1, bool butt2)
{
	static bool moving = false;
	if(butt1 == true && moving == false)
	{
		motor[spinner] = 100;
		moving = true;
	}

	else if(butt1 == true && moving == true)
	{
		motor[spinner] = 0;
		moving = false;
	}

	else if(butt2 == true && moving == false)
	{
		motor[spinner] = -100;
		moving = true;
	}
	else if(butt2 == true && moving ==true)
	{
		motor[spinner] = 0;
		moving = false;
	}
}

task main()
{
 if(joy1Btn(1) == true || joy1Btn(2) == true)
 {
   spin(joy1Btn(1), joy1Btn(2));
 }

}
