#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     seeker,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftFront,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     rightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    rampDrop,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    rampLease,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    tail,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    drawBridge,           tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment 4.X\Sample Programs\NXT\3rd Party Driver Library\include\hitechnic-irseeker-v2.h"
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
const int tailInitial = 20;
const int rampInitial = 127;
const int leaseInitial = 127;
const float countPF = 720.0;
const float speedScale = .84;
const float CPD = 12.5;
const float SPEED = 50;
// Create struct to hold sensor data
tHTIRS2 irSeeker;


void initializeRobot()
{
	//eraseDisplay();
	//nMotorEncoder[leftBack] = 0;
	//nMotorEncoder[rightFront] = 0;
	//servo[rampLease] = leaseInitial;
	//servo[tail] = tailInitial;
	//servo[rampDrop] = rampInitial;
	nMotorEncoder[lift] = 0;
	nMotorEncoder[leftFront] = 0;
	nMotorEncoder[rightFront] = 0;
	//clearDebugStream();
  // Initialise and configure struct and port
  initSensor(&irSeeker, seeker);
 // startTask(irSeek);

}


void moveForward(float ft)
{
	while(nMotorEncoder[leftFront] <= (ft * countPF))
	{
		motor[leftBack] = SPEED;
		motor[rightBack] = SPEED *speedScale;
		motor[leftFront] = SPEED;
		motor[rightFront] = SPEED * speedScale;
		writeDebugStreamLine("X: %d", nMotorEncoder[leftFront]);
	}

	motor[leftBack] = 0;
	motor[rightBack] = 0;
	motor[leftFront] = 0;
	motor[rightFront] = 0;
	nMotorEncoder[leftFront] = 0;
	nMotorEncoder[rightFront] = 0;
}

void moveBackward(float ft)
{
	while(nMotorEncoder[leftFront] >= (-ft * countPF))
	{
		motor[leftBack] = -48;
		motor[rightBack] = -40;
		motor[leftFront] = -48;
		motor[rightFront] = -40;
		writeDebugStreamLine("X: %d", nMotorEncoder[leftFront]);
	}
	motor[leftBack] = 0;
	motor[rightBack] = 0;
	motor[leftFront] = 0;
	motor[rightFront] = 0;
	nMotorEncoder[leftFront] = 0;
	nMotorEncoder[rightFront] = 0;
}

void turnLeft(float degree)
{
	while(nMotorEncoder[leftFront] >= (-degree * CPD) && nMotorEncoder[rightFront] <= (degree * CPD))
	{
		motor[leftBack] = -75;
		motor[rightBack] = 63;
		motor[leftFront] = -75;
		motor[rightFront] = 63;
		writeDebugStreamLine("X: %d", nMotorEncoder[leftFront]);
	}
	motor[leftBack] = 0;
	motor[rightBack] = 0;
	motor[leftFront] = 0;
	motor[rightBack] = 0;
	nMotorEncoder[leftFront] = 0;
	nMotorEncoder[rightFront] = 0;
}

void turnRight(float degree)
{
 while(nMotorEncoder[leftFront] <= (degree * CPD) && nMotorEncoder[rightFront] >= (-degree * CPD))
 {
		motor[leftBack] = 75;
		motor[rightBack] = -75;
		motor[leftFront] = 75;
		motor[rightFront] = -75;
		writeDebugStreamLine("X: %d", nMotorEncoder[leftFront]);
 }
  	motor[leftBack] = 0;
		motor[rightBack] = 0;
		motor[leftFront] = 0;
		motor[rightFront] = 0;
		nMotorEncoder[leftFront] = 0;
		nMotorEncoder[rightFront] = 0;
}

void stopBot()
{
	motor[leftBack] = 0;
	motor[rightBack] = 0;
	motor[leftFront] = 0;
	motor[rightFront] = 0;
}

//void raiseLift()
//{
/* while(nMotorEncoder[lift] < 100)
 {
   motor[lift] = 68;
 }
 motor[lift] = 0;
 nMotorEncoder[lift] = 0;
}*/

void lowerLift()
{
	motor[lift] = -50;
	wait10Msec(200);
  motor[lift] = 0;
}

void IRseeker()
{
	  playSound(soundBlip);
    readSensor(&irSeeker);        //read the IR seeker
    playSound(soundException);
	  displayTextLine(1, "D:%4d", irSeeker.acDirection);
	  if(irSeeker.acDirection == 5)
	  {
	  	playSound(soundBeepBeep);
	  }
	  else if(irSeeker.acDirection == 7)
	  {
	  	playSound(soundDownwardTones);
	  }
	  else
	  {

	  }
}


task main()
{
  motor[lift] = 0;
	//waitForStart();
	//irSeeker.acDirection;
	initializeRobot();

	moveBackward(7.5);
	stopBot();
	wait10Msec(100);
	turnLeft(130);
	wait10Msec(75);
  moveBackward(2.50);
  wait10Msec(75);
	IRseeker();









}
