#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S4_C1_1,     motorLF,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     motorRF,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorLB,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     motorRB,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     Spinners,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     Lifter,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    PinPad,               tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    Dumper,               tServoStandard)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h";									//Include file that allows our IR seeker to work properly


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																														//
//																								Autonomous Ramp Plan:																												//
//																																																														//
//	1.Set up Robot for competition.																																														//
//																																																														//
//	2.Drive down ramp using gyroscopic sensor and motor encoders.																															//
//																																																														//
//	3.Take IR reading to determine center goal position.																																			//
//																																																														//
//	4.Drive to 60cm rolling goal/Attach using gyroscopic sensor and motor encoders.																						//
//																																																														//
//	5.Drive to Parking Zone using gyroscopic sensor and motor encoders.																												//
//																																																														//
//	6.Release 60 cm rolling goal in Parking Zone.																																							//
//																																																														//
//	7.Score in Center Field Structure using gyroscopic sensor and motor encoders based upon previous IR reading.							//
//																																																														//
//	8.Drive to and knock over Kickstand, using gyroscopic sensor and motor encoders based upon previous IR reading.						//
//																																																														//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																														//
//																								Autonomous Ramp Back-up Plan:																												//
//																																																														//
//	1.Set up Robot for competition.																																														//
//																																																														//
//	2.Drive down ramp using gyroscopic sensor and motor encoders.																															//
//																																																														//
//	3.IR reading resulted in error, Center goal position is unknown.																													//
//																																																														//
//	4.Drive to 60cm rolling goal/Attach/Score using gyroscopic sensor and motor encoders.																			//
//																																																														//
//	5.Drive to Parking Zone using gyroscopic sensor and motor encoders.																												//
//																																																														//
//	6.Release 60 cm rolling goal in Parking Zone.																																							//
//																																																														//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
		nMotorEncoder[motorRF] = 0;													//Reset Motor Encoders
		nMotorEncoder[motorRB] = 0;
		nMotorEncoder[motorLF] = 0;
		nMotorEncoder[motorLB] = 0;
}

void SetUp()
{
		// Drop Spinners, calibrate moving parts if needed
	return;
}

void Movement(float MR, float ML, float R, float L)
{
		nMotorEncoderTarget[motorRF]=1440*MR;														//MR sets the amount of revolutions the motor should make
		nMotorEncoderTarget[motorRB]=1440*MR;
		nMotorEncoderTarget[motorLF]=1440*ML;														//ML sets the amount of revolutions the motor should make
		nMotorEncoderTarget[motorLB]=1440*ML;


		motor[motorRF] = (R);																						//R is the motor power level for the right side
		motor[motorRB] = (R);
		motor[motorLF] = (L);																						//L is the motor power level for the left side
		motor[motorLB] = (L);

		nMotorEncoderTarget[motorRF]=0;																	//Reset motor encoders
		nMotorEncoderTarget[motorRB]=0;
		nMotorEncoderTarget[motorLF]=0;
		nMotorEncoderTarget[motorLB]=0;

		motor[motorRF] = 0;																							//Turn off all motors
		motor[motorRB] = 0;
		motor[motorLF] = 0;
		motor[motorLB] = 0;

	return;																														//Return to the last line of code called
}

void Kickstand(){																										//Code to be used to knock down the kickstand

		Movement(0.5,0.5,50,50);																				//Forward half a square
		Movement(0.25,-0.25,50,-50);																		//90 degree Left Turn
		Movement(0.5,0.5,50,50);																				//Forward half a square
		Movement(-0.25,0.25,-50,50);																		//90 degree Right Turn
		Movement(-2,-2,-50,-50);																				//Back up two squares

}

task main()
{

	initializeRobot();

  tHTIRS2 irSeeker;																									//Calibrates the IR seeker
	initSensor(&irSeeker, S1);

	int CenterPosition = 0;																						//The Center Position is the position of the Center Field Stucture

//	waitForStart();

		SetUp();

	Movement(-3.25,-3.25,-50,-50);																		//Drive off ramp

  wait1Msec(250);

    readSensor(&irSeeker);																					//read the IR seeker
	  displayTextLine(1, "D:%4d", irSeeker.acDirection);							//display direction of IR beacon on screen

		if (irSeeker.acDirection == 4)
		{
		  displayTextLine(2, " CF = 1");
		  CenterPosition = 1;																						//Center Field Structure is 1
		  wait1Msec(150);
		}

		else if (irSeeker.acDirection == 5)
		{
		  displayTextLine(2, " CF = 2");
			CenterPosition = 2;																						//Center Field Structure is 2
			wait1Msec(150);
	  }

	  else if (irSeeker.acDirection == 6)
	  {
	  	displayTextLine(2, " CF = 3");
			CenterPosition = 3;																						//Center Field Structure
			wait1Msec(150);
	  }

	  else {
	  	displayTextLine(2, "IR failure!");														//IR did not read a value it should have
	  	playSound(soundException);																		//activate back-up plan
	  	CenterPosition = 0;
	  	wait1Msec(150);
	  }

	//Drop PinPad

	  Movement(-0.15,0.15,-50,50);																		//Angle robot to face Parking Zone
	  Movement(5,5,50,50);																						//Drive to Parking Zone
	  Movement(-0.35,0.35,-50,50);																		//Rotate to put Rolling goal into Parking Zone

	  if(CenterPosition == 0){																				//If Center Field Structure is unknown activate back-up plan
	  	//Drop Bucket
	}

		else{
		wait1Msec(50);
	}

  //Raise PinPad

	 switch(CenterPosition)																						//Switch Cases based upon CenterPosition's IR reading
 {
  case 1:                // if 'CenterPosition' is '1':

  	Movement(0.25,-0.25,50,-50);																		//90 degree Left Turn
  	Movement(2,2,50,50);																						//Forward two squares
		Movement(-0.25,0.25,-50,50);																		//90 degree Right Turn
		Movement(1.5,1.5,50,50);																				//Forward 1.5 squares
		Movement(0.25,-0.25,50,-50);																		//90 degree Left Turn
		Movement(-0.5,-0.5,-50,-50);																		//Back up half a sqare

		//Drop Bucket

		Kickstand();

		break;                 					// break out of this switch statement and continue code after the '}'

  case 2:                						// if 'CenterPosition' is '2':

			Movement(0.25,-0.25,50,-50);																	//90 degree Left Turn
			Movement(2,2,50,50);																					//Forward two squares
			Movement(0.15,-0.15,50,-50);																	//a careful Left Turn
			Movement(-0.5,-0.5,-50,-50);																	//Back up half a square

		//Drop Bucket

		Kickstand();

  break;                 // break out of this switch statement and continue code after the '}'

  case 3:								 // if 'CenterPosition' is '3':

    Movement(0.25,-0.25,50,-50);																		//90 degree Left Turn
  	Movement(0.5,0.5,50,50);																				//Half a step forward
  	Movement(0.25,-0.25,50,-50);																		//90 degree Left Turn
		Movement(-0.5,-0.5,-50,-50);																		//Half a step backward

		//Drop Bucket

		Kickstand();

  break;								 // break out of this switch statement and continue code after the '}'

		  default:               // if IR misread, then do not move
		Movement(0,0,0,0);

		break;

 }
 playSound(soundFastUpwardTones);																		//Victory Sound

}
