#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftFront,     tmotorTetrix, openLoop, encoder, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     rightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    rampDrop,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    rampLease,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    tail,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    drawBridge,           tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
const int tailInitial = 20;
const int rampInitial = 127;
const int leaseInitial = 127;


void initializeRobot()
{
	eraseDisplay();
	nMotorEncoder[leftFront] = 0;
	nMotorEncoder[rightFront] = 0;
	servo[rampLease] = leaseInitial;
	servo[tail] = tailInitial;
	servo[rampDrop] = rampInitial;
	nMotorEncoder[lift] = 0;
	clearDebugStream();
}



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
task main()
{
	while(true)
 {
   initializeRobot();


  	while(nMotorEncoder[leftFront] < 1440 || nMotorEncoder[rightFront] < 1440)
  		{
        motor[leftFront] = 25;
				motor[rightFront] = 25;
  			motor[leftBack] = 25;
  			motor[rightBack] = 25;
  		}

    nMotorEncoder[leftFront] = 0;
  	nMotorEncoder[rightFront] = 0;
    motor[leftFront] = 0;
		motor[rightFront] = 0;
  	motor[leftBack] = 0;
  	motor[rightBack] = 0;


  }


}
