#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     mo,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     bo,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1)
  {
  	motor[mo] = -100;
  	motor[bo] = 100;
  }
}
